name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Update package repositories and install aidl
      - name: Update packages and install aidl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y aidl

      # Copy aidl to the specified directory
      - name: Copy aidl to Buildozer directory
        run: |
          sudo cp `which aidl` /home/aca/.buildozer/android/platform/android-sdk/build-tools/30.0.0-rc4/aidl

      # Cache the Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      # Cache the Buildozer directory with a timestamp
      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Build the Android application with Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # Upload the built artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
